/**
 * Hierarchical Regional Geospatial Data for FindLostPuppy
 * States: Andhra Pradesh (26 reorganized districts), Telangana (33 reorganized districts), Karnataka (31 districts)
 * ALL districts and mandals are strictly sorted in ALPHABETICAL ORDER (A-Z).
 */

export interface StateGeoData {
  [district: string]: string[];
}

export const SUPPORTED_STATES = ['Andhra Pradesh', 'Telangana', 'Karnataka'] as const;
export type SupportedState = (typeof SUPPORTED_STATES)[number];

export const REGIONAL_GEO_DATA: Record<SupportedState, StateGeoData> = {
  'Andhra Pradesh': {
    'Alluri Sitharama Raju': [
      'Addateegala',
      'Ananthagiri',
      'Araku Valley',
      'Chintapalli',
      'Chintoor',
      'Devipatnam',
      'Dumbriguda',
      'G.K.Veedhi',
      'G.Madugula',
      'Gangavaram',
      'Hukumpeta',
      'Koonavaram',
      'Koyyuru',
      'Maredumilli',
      'Munchingiputtu',
      'Paderu',
      'Peda Bayalu',
      'Rajavommangi',
      'Rampachodavaram',
      'Vararamachandrapuram',
      'Y.Ramavaram',
    ],
    'Anakapalli': [
      'Anakapalli',
      'Atchutapuram',
      'Butchayyapeta',
      'Cheedikada',
      'Chodavaram',
      'Devarapalle',
      'K.Kotapadu',
      'Kasimkota',
      'Kotauratla',
      'Makavarapalem',
      'Munagapaka',
      'Nakkapalle',
      'Narsipatnam',
      'Paravada',
      'Payakaraopeta',
      'Rambilli',
      'Ravikamatham',
      'Rolugunta',
      'S.Rayavaram',
      'Yelamanchili',
    ],
    'Ananthapuramu (Anantapur)': [
      'Anantapur',
      'Anantapur Rural',
      'Atmakur',
      'Beluguppa',
      'Bommanahal',
      'Bramhasamudram',
      'Bukkarayasamudram',
      'D.Hirehal',
      'Garladinne',
      'Gooty',
      'Gummagatta',
      'Guntakal',
      'Kalyandurg',
      'Kambhadur',
      'Kanaganapalli',
      'Kudair',
      'Kundurpi',
      'Narpala',
      'Pamidi',
      'Peddapappur',
      'Peddavadugur',
      'Putlur',
      'Rapthadu',
      'Rayadurg',
      'Settur',
      'Singanamala',
      'Tadimarri',
      'Tadipatri',
      'Uravakonda',
      'Vajrakarur',
      'Vidapanakal',
      'Yadiki',
      'Yellanur',
    ],
    'Annamayya': [
      'B.Kothakota',
      'Chinnamandem',
      'Galiveedu',
      'Gurramkonda',
      'K.V.Palli',
      'Kalakada',
      'Kalikiri',
      'Kurabalakota',
      'Madanapalle',
      'Nimmanapalle',
      'Peddamandyam',
      'Pileru',
      'Rajampet',
      'Ramapuram',
      'Rayachoti',
      'Sambepalli',
      'Thamballapalle',
      'Valmikipuram',
      'Veeraballi',
    ],
    'Bapatla': [
      'Addanki',
      'Amruthalur',
      'Bapatla',
      'Bhattiprolu',
      'Chinaganjam',
      'Chirala',
      'Inkollu',
      'Karamchedu',
      'Martur',
      'Nagaram',
      'Nizampatnam',
      'Panguluru',
      'Parchur',
      'Repalle',
      'Santhamaguluru',
      'Tsundur',
      'Vetapalem',
      'Yeddanapudi',
    ],
    'Chittoor': [
      'Bangarupalem',
      'Bireddypalli',
      'Chittoor',
      'Chowdepalli',
      'Gangadhara Nellore',
      'Gudipala',
      'Irala',
      'Karvetinagar',
      'Kuppam',
      'Nagari',
      'Palamaner',
      'Penumuru',
      'Pulicherla',
      'Punganur',
      'Rallabudugur',
      'Ramakuppam',
      'Santhipuram',
      'Somala',
      'Srirangarajapatnam',
      'Thavanampalle',
      'Vedurukuppam',
      'Venkatagirikota',
      'Vijayapuram',
      'Yadamari',
    ],
    'Dr. B.R. Ambedkar Konaseema': [
      'Ainavilli',
      'Allavaram',
      'Amalapuram',
      'Ambajipeta',
      'Atreyapuram',
      'Kapileswarapuram',
      'Katrenikona',
      'Kothapeta',
      'Malikipuram',
      'Mandapeta',
      'Mummidivaram',
      'P.Gannavaram',
      'Ramachandrapuram',
      'Ravulapalem',
      'Rayavaram',
      'Razole',
      'Sakhinetipalli',
      'Uppalaguptam',
    ],
    'East Godavari': [
      'Anaparthi',
      'Biccavolu',
      'Chagallu',
      'Devarapalle',
      'Gokavaram',
      'Gopalapuram',
      'Korukonda',
      'Kovvur',
      'Nidadavole',
      'Peravali',
      'Rajamahendravaram (Urban)',
      'Rajahmundry Rural',
      'Rangampeta',
      'Seethanagaram',
      'Tallapudi',
    ],
    'Eluru': [
      'Bhimadole',
      'Buttayagudem',
      'Chintalapudi',
      'Denduluru',
      'Dwaraka Tirumala',
      'Eluru',
      'Jangareddigudem',
      'Jeelugumilli',
      'Kalidindi',
      'Kamavarapukota',
      'Koyyalagudem',
      'Kukunoor',
      'Mandavalli',
      'Mudinepalli',
      'Musunuru',
      'Nidamarru',
      'Nuzvid',
      'Pedapadu',
      'Pedavegi',
      'Polavaram',
      'T.Narasapuram',
      'Unguturu',
      'Velairpadu',
    ],
    'Guntur': [
      'Chebrolu',
      'Duggirala',
      'Guntur East',
      'Guntur West',
      'Kakumanu',
      'Kollipara',
      'Mangalagiri',
      'Medikonduru',
      'Pedakakani',
      'Pedanandipadu',
      'Phirangipuram',
      'Ponnur',
      'Prathipadu',
      'Tadepalli',
      'Tadikonda',
      'Tenali',
      'Vatticherukuru',
    ],
    'Kakinada': [
      'Gandepalli',
      'Gollaprolu',
      'Jaggampeta',
      'Kajuluru',
      'Kakinada Rural',
      'Kakinada Urban',
      'Karapa',
      'Kotananduru',
      'Peddapuram',
      'Pithapuram',
      'Prathipadu',
      'Rowthulapudi',
      'Samalkota',
      'Sankhavaram',
      'Thondangi',
      'Tuni',
      'U.Kothapalli',
      'Yeleswaram',
    ],
    'Krishna': [
      'Avanigadda',
      'Bantumilli',
      'Challapalli',
      'Ghantasala',
      'Gudivada',
      'Gudlavalleru',
      'Guduru',
      'Kaikaluru',
      'Kruthivennu',
      'Machilipatnam',
      'Mopidevi',
      'Movva',
      'Nagayalanka',
      'Nandivada',
      'Pamarru',
      'Pedana',
      'Pedaparupudi',
      'Vuyyuru',
    ],
    'Kurnool': [
      'Adoni',
      'Alur',
      'Aspari',
      'C.Belagal',
      'Devanakonda',
      'Gonegandla',
      'Gudur',
      'Halaharvi',
      'Holagunda',
      'Kallur',
      'Kodumur',
      'Kosigi',
      'Kowthalam',
      'Kurnool Rural',
      'Kurnool Urban',
      'Maddikera',
      'Mantralayam',
      'Nandavaram',
      'Orvakal',
      'Pattikonda',
      'Tuggali',
      'Veldurthi',
      'Yemmiganur',
    ],
    'Nandyal': [
      'Allagadda',
      'Atmakur',
      'Banaganapalle',
      'Bethamcherla',
      'Chagalamarri',
      'Dhone',
      'Dornipadu',
      'Gadivemula',
      'Gospadu',
      'Jupadu Bungalow',
      'Koilkuntla',
      'Kolimigundla',
      'Kothapalle',
      'Mahanandi',
      'Midthur',
      'Nandikotkur',
      'Nandyal',
      'Owk',
      'Panyam',
      'Peapally',
      'Rudravaram',
      'Sanjamala',
      'Sirvella',
      'Srisailam',
      'Uyyalawada',
      'Velgodu',
    ],
    'NTR (Vijayawada)': [
      'A.Konduru',
      'Chandarlapadu',
      'G.Konduru',
      'Ibrahimpatnam',
      'Jaggaiahpet',
      'Kanchikacherla',
      'Mylavaram',
      'Nandigama',
      'Penuganchiprolu',
      'Reddigudem',
      'Tiruvuru',
      'Vatsavai',
      'Veerullapadu',
      'Vijayawada Rural',
      'Vijayawada Urban',
      'Vissannapeta',
    ],
    'Palnadu': [
      'Bellamkonda',
      'Bollapalle',
      'Chilakaluripet',
      'Dachepalle',
      'Gurazala',
      'Karempudi',
      'Macherla',
      'Muppalla',
      'Nadendla',
      'Narasaraopet',
      'Nekarikallu',
      'Piduguralla',
      'Rajupalem',
      'Rentachintala',
      'Rompicherla',
      'Sattenapalle',
      'Savalyapuram',
      'Vinukonda',
    ],
    'Parvathipuram Manyam': [
      'Balijipeta',
      'Bhamini',
      'Garugubilli',
      'Gummalakshmipuram',
      'Jiyyammavalasa',
      'Komarada',
      'Kurupam',
      'Makkuva',
      'Pachipenta',
      'Palakonda',
      'Parvathipuram',
      'Salur',
      'Seethampeta',
      'Seethanagaram',
      'Veeraghattam',
    ],
    'Prakasam': [
      'C.S.Puram',
      'Chimakurthy',
      'Darsi',
      'Donakonda',
      'Giddalur',
      'Hanumantunipadu',
      'Kandukur',
      'Kanigiri',
      'Konakanamitla',
      'Kothapatnam',
      'Maddipadu',
      'Markapur',
      'Marripudi',
      'Mundlamuru',
      'Naguluppalapadu',
      'Ongole',
      'Pamur',
      'Peda Araveedu',
      'Podili',
      'Ponnaluru',
      'Racherla',
      'Santhanuthalapadu',
      'Singarayakonda',
      'Tangutur',
      'Tarlupadu',
      'Tripurantakam',
      'Veligandla',
      'Yerragondapalem',
      'Zarugumalli',
    ],
    'SPSR Nellore': [
      'Allur',
      'Ananthasagaram',
      'Atmakur',
      'Bogole',
      'Butchireddipalem',
      'Dagadarthi',
      'Indukurpet',
      'Jaladanki',
      'Kaligiri',
      'Kaluvoya',
      'Kavali',
      'Kodavalur',
      'Kondapuram',
      'Kovur',
      'Manubolu',
      'Marripadu',
      'Muthukur',
      'Nellore Rural',
      'Nellore Urban',
      'Podalakur',
      'Rapur',
      'Sangam',
      'Thotapalligudur',
      'Venkatachalam',
      'Vidavalur',
      'Vinjamur',
    ],
    'Sri Sathya Sai': [
      'Agali',
      'Amadagur',
      'Amarapuram',
      'Bukkapatnam',
      'Chennekothapalle',
      'Chilamathur',
      'Dharmavaram',
      'Gandlapenta',
      'Gorantla',
      'Gudibanda',
      'Hindupur',
      'Kadiri',
      'Kothacheruvu',
      'Lepakshi',
      'Madakasira',
      'Mudigubba',
      'Nallamada',
      'O.D.Cheruvu',
      'Parigi',
      'Penukonda',
      'Puttaparthi',
      'Roddam',
      'Rolla',
      'Somandepalle',
      'Talupula',
      'Tanakal',
    ],
    'Srikakulam': [
      'Amadalavalasa',
      'Etcherla',
      'Gara',
      'Hiramandalam',
      'Ichchapuram',
      'Jalumuru',
      'Kanchili',
      'Kaviti',
      'Kotabommali',
      'Kothuru',
      'Laxminarasupeta',
      'Mandasa',
      'Meliaputti',
      'Nandigam',
      'Narasannapeta',
      'Palasa',
      'Pathapatnam',
      'Polaki',
      'Ponduru',
      'Ranastalam',
      'Santhabommali',
      'Saravakota',
      'Sarubujjili',
      'Sompeta',
      'Srikakulam',
      'Tekkali',
      'Vajrapukothuru',
    ],
    'Tirupati': [
      'Balayapalli',
      'Chandragiri',
      'Chillakur',
      'Chittamur',
      'Dakkili',
      'Doravarisatram',
      'Gudur',
      'Kota',
      'Naidupeta',
      'Ozili',
      'Pellakur',
      'Puttur',
      'Renigunta',
      'Srikalahasti',
      'Sullurpeta',
      'Tada',
      'Tirupati Rural',
      'Tirupati Urban',
      'Vakadu',
      'Varadaiahpalem',
      'Venkatagiri',
      'Yerpedu',
    ],
    'Visakhapatnam': [
      'Anandapuram',
      'Bheemunipatnam',
      'Gajuwaka',
      'Gopalapatnam',
      'Maharani Peta',
      'Mulagada',
      'Padmanabham',
      'Pedagantyada',
      'Pendurthi',
      'Seethammadhara',
      'Visakhapatnam Urban',
    ],
    'Vizianagaram': [
      'Badangi',
      'Bobbili',
      'Bondapalle',
      'Cheepurupalli',
      'Dattirajeru',
      'Denkada',
      'Gajapathinagaram',
      'Gantyada',
      'Garividi',
      'Gurla',
      'Jami',
      'Kothavalasa',
      'Lakkavarapukota',
      'Merakamudidam',
      'Nellimarla',
      'Pusapatirega',
      'Rajam',
      'Ramabhadrapuram',
      'Santhakaviti',
      'Srungavarapukota',
      'Therlam',
      'Vangara',
      'Vepada',
      'Vizianagaram',
    ],
    'West Godavari': [
      'Achanta',
      'Akividu',
      'Attili',
      'Bhimavaram',
      'Iragavaram',
      'Kalla',
      'Mogalthur',
      'Narasapuram',
      'Palakollu',
      'Pentapadu',
      'Penugonda',
      'Penumantra',
      'Poduru',
      'Tadepalligudem',
      'Tanuku',
      'Undrajavaram',
      'Veeravasaram',
      'Yelamanchili',
    ],
    'YSR Kadapa': [
      'Badvel',
      'Chakrayapet',
      'Chapadu',
      'Chennur',
      'Chinthakommadinne',
      'Duvvur',
      'Jammalamadugu',
      'Kadapa',
      'Kamalapuram',
      'Kondapuram',
      'Lingala',
      'Muddanur',
      'Mydukur',
      'Mylavaram',
      'Pendlimarri',
      'Proddatur',
      'Pulivendula',
      'Rajupalem',
      'Simhadripuram',
      'Thondur',
      'Vallur',
      'Veerapunayunipalle',
      'Vempalli',
      'Vemula',
      'Yerraguntla',
    ],
  },
  'Telangana': {
    'Adilabad': [
      'Adilabad Rural',
      'Adilabad Urban',
      'Bazarhathnoor',
      'Bela',
      'Bheempur',
      'Boath',
      'Gudihathnoor',
      'Ichoda',
      'Indervelly',
      'Jainad',
      'Mavala',
      'Narnoor',
      'Neradigonda',
      'Sirikonda',
      'Talamadugu',
      'Tamsi',
      'Utnoor',
    ],
    'Bhadradri Kothagudem': [
      'Allapalli',
      'Annapureddypally',
      'Aswapuram',
      'Aswaraopeta',
      'Bhadrachalam',
      'Burgampahad',
      'Chandrugonda',
      'Cherla',
      'Chunchupalle',
      'Dammapeta',
      'Dummugudem',
      'Gundala',
      'Julurpad',
      'Karakagudem',
      'Kothagudem',
      'Laxmidevipalli',
      'Manuguru',
      'Mulakalapalle',
      'Palwancha',
      'Pinapaka',
      'Sujathanagar',
      'Tekulapalli',
      'Yellandu',
    ],
    'Hanamkonda': [
      'Bheemadevarpalli',
      'Dharmasagar',
      'Elkathurthy',
      'Hanamkonda',
      'Hasanparthy',
      'Inavolu',
      'Kamalapur',
      'Kazipet',
      'Nadikuda',
      'Parkal',
      'Shayampet',
      'Velair',
    ],
    'Hyderabad': [
      'Amberpet',
      'Ameerpet',
      'Asifnagar',
      'Bahadurpura',
      'Bandlaguda',
      'Begumpet',
      'Charminar',
      'Golconda',
      'Himayathnagar',
      'Jubilee Hills',
      'Khairatabad',
      'Marredpally',
      'Musheerabad',
      'Nampally',
      'Saidabad',
      'Secunderabad',
      'Shaikpet',
      'Tirumalagiri',
    ],
    'Jagtial': [
      'Beerpur',
      'Buggaram',
      'Dharmapuri',
      'Gollapalli',
      'Ibrahimpatnam',
      'Jagtial',
      'Jagtial Rural',
      'Kathlapur',
      'Kodimial',
      'Korutla',
      'Malial',
      'Mallapur',
      'Medipalli',
      'Metpally',
      'Pegadapalli',
      'Raikal',
      'Sarangapur',
      'Velgatoor',
    ],
    'Jangaon': [
      'Bachannapeta',
      'Devaruppula',
      'Gundala',
      'Jangaon',
      'Lingalaghanpur',
      'Narmetta',
      'Palakurthi',
      'Raghunathpalle',
      'Station Ghanpur',
      'Tarigoppula',
      'Zaffergadh',
    ],
    'Jayashankar Bhupalpally': [
      'Bhupalpally',
      'Chityal',
      'Ghanpur',
      'Kataram',
      'Mahadevpur',
      'Malhar Rao',
      'Mogullapally',
      'Mutharam',
      'Palimela',
      'Regonda',
      'Tekumatla',
    ],
    'Jogulamba Gadwal': [
      'Alampur',
      'Dharur',
      'Gadwal',
      'Gattu',
      'Ieeja',
      'Itikyal',
      'Kaloor Timmanadoddi',
      'Maldakal',
      'Manopad',
      'Rajoli',
      'Undavelly',
      'Waddepally',
    ],
    'Kamareddy': [
      'Banswada',
      'Bhiknoor',
      'Birkoor',
      'Domakonda',
      'Gandhari',
      'Jukkal',
      'Kamareddy',
      'Lingampet',
      'Machareddy',
      'Madnoor',
      'Nasrullabad',
      'Nizamsagar',
      'Pedda Kodapgal',
      'Pitlam',
      'Rajampet',
      'Ramareddy',
      'Sadashivanagar',
      'Tadwai',
      'Yellareddy',
    ],
    'Karimnagar': [
      'Chigurumamidi',
      'Choppadandi',
      'Ellanthakunta',
      'Gangadhara',
      'Ganneruvaram',
      'Huzurabad',
      'Jammikunta',
      'Karimnagar',
      'Karimnagar Rural',
      'Kothapalli',
      'Manakondur',
      'Ramadugu',
      'Saidapur',
      'Shankarapatnam',
      'Thimmapur',
      'Veenavanka',
    ],
    'Khammam': [
      'Bonakal',
      'Chintakani',
      'Enkoor',
      'Kalluru',
      'Kamepally',
      'Khammam Rural',
      'Khammam Urban',
      'Konijerla',
      'Kusumanchi',
      'Madhira',
      'Mudigonda',
      'Nelakondapally',
      'Penuballi',
      'Raghunathapalem',
      'Sathupalli',
      'Singareni',
      'Tallada',
      'Thirumalayapalem',
      'Vemsoor',
      'Wyra',
      'Yerrupalem',
    ],
    'Kumuram Bheem Asifabad': [
      'Asifabad',
      'Bejjur',
      'Chintalamanepally',
      'Dahegaon',
      'Jainoor',
      'Kagaznagar',
      'Kerameri',
      'Kouthala',
      'Lingapur',
      'Penchikalpet',
      'Rebbena',
      'Sirpur (T)',
      'Sirpur (U)',
      'Tiryani',
      'Wankidi',
    ],
    'Mahabubabad': [
      'Bayyaram',
      'Chinnagudur',
      'Danthalapalle',
      'Dornakal',
      'Gangaram',
      'Garla',
      'Gudur',
      'Kesamudram',
      'Kothaguda',
      'Kuravi',
      'Mahabubabad',
      'Maripeda',
      'Narsimhulapet',
      'Nellikudur',
      'Seerole',
    ],
    'Mahabubnagar': [
      'Addakal',
      'Balanagar',
      'Bhoothpur',
      'Chinna Chintakunta',
      'Devarakadra',
      'Gandeed',
      'Hanwada',
      'Jadcherla',
      'Koilkonda',
      'Kothakota',
      'Mahabubnagar Rural',
      'Mahabubnagar Urban',
      'Midjil',
      'Mohammadabad',
      'Moosapet',
      'Nawabpet',
      'Rajapur',
    ],
    'Mancherial': [
      'Bellampalli',
      'Bheemaram',
      'Bheemini',
      'Chennur',
      'Dandepally',
      'Hajipur',
      'Jaipur',
      'Jannaram',
      'Kannepally',
      'Kasipet',
      'Kotapally',
      'Luxettipet',
      'Mancherial',
      'Mandamarri',
      'Naspur',
      'Nennal',
      'Tandur',
      'Vemanpally',
    ],
    'Medak': [
      'Alladurg',
      'Chegunta',
      'Chilipched',
      'Havelighanpur',
      'Kowdipalle',
      'Kulcharam',
      'Manoharabad',
      'Masaipet',
      'Medak',
      'Narsapur',
      'Nizampet',
      'Papannapet',
      'Ramayampet',
      'Regode',
      'Shankarampet (A)',
      'Shankarampet (R)',
      'Shivampet',
      'Tekmal',
      'Tupran',
      'Yeldurthy',
    ],
    'Medchal-Malkajgiri': [
      'Alwal',
      'Bachupally',
      'Balanagar',
      'Dundigal Gandimaisamma',
      'Ghatkesar',
      'Kapra',
      'Keesara',
      'Kukatpally',
      'Malkajgiri',
      'Medchal',
      'Medipally',
      'Muduchintalpalli',
      'Quthbullapur',
      'Shamirpet',
      'Uppal',
    ],
    'Mulugu': [
      'Eturnagaram',
      'Govindaraopet',
      'Kannaigudem',
      'Mangapet',
      'Mulugu',
      'Tadvai (Sammakka Sarakka)',
      'Venkatapur',
      'Venkatapuram',
      'Wazeed',
    ],
    'Nagarkurnool': [
      'Achampet',
      'Alampur',
      'Amrabad',
      'Balmoor',
      'Bijinapalle',
      'Charakonda',
      'Kalwakurthy',
      'Kollapur',
      'Lingal',
      'Nagarkurnool',
      'Padara',
      'Peddakothapalle',
      'Pentlavelli',
      'Telkapally',
      'Thimmajipet',
      'Urkonda',
      'Vangoor',
      'Vepangandla',
    ],
    'Nalgonda': [
      'Anumula (Haliya)',
      'Chandampet',
      'Chandur',
      'Chityal',
      'Damaracherla',
      'Devarakonda',
      'Dindi',
      'Gundlapally',
      'Gurrampode',
      'Kanagal',
      'Kattangur',
      'Kethepally',
      'Madugulapally',
      'Marriguda',
      'Miryalaguda',
      'Munugode',
      'Nakrekal',
      'Nalgonda',
      'Narketpally',
      'Neredugommu',
      'Nidamanoor',
      'Peddavoora',
      'Saligowraram',
      'Thipparthy',
      'Tirumalagiri Sagar',
      'Tripuraram',
      'Vemulapally',
    ],
    'Narayanpet': [
      'Damaragidda',
      'Dhanwada',
      'Kosgi',
      'Krishna',
      'Maddur',
      'Maganoor',
      'Makthal',
      'Marikal',
      'Narayanpet',
      'Narva',
      'Utkoor',
    ],
    'Nirmal': [
      'Basar',
      'Bhainsa',
      'Dasturabad',
      'Dilawarpur',
      'Kaddam (Peddur)',
      'Khanapur',
      'Kubeer',
      'Kuntala',
      'Laxmanchanda',
      'Lokeshwaram',
      'Mamda',
      'Mudhole',
      'Narsapur (G)',
      'Nirmal Rural',
      'Nirmal Urban',
      'Pembi',
      'Sarangapur',
      'Soan',
      'Tanur',
    ],
    'Nizamabad': [
      'Armoor',
      'Balkonda',
      'Bheemgal',
      'Bodhan',
      'Chandur',
      'Dharpally',
      'Dichpally',
      'Donkeshwar',
      'Edapally',
      'Indalwai',
      'Jakranpally',
      'Kotgiri',
      'Makloor',
      'Mendora',
      'Mopal',
      'Mosra',
      'Mugpal',
      'Navipet',
      'Nizamabad North',
      'Nizamabad Rural',
      'Nizamabad South',
      'Renjal',
      'Rudrur',
      'Sirikonda',
      'Varni',
      'Velpur',
      'Yedapally',
    ],
    'Peddapalli': [
      'Anthergaon',
      'Dharmaram',
      'Eligandu',
      'Julapalle',
      'Kamanpur',
      'Manthani',
      'Mutharam',
      'Odela',
      'Palakurthy',
      'Peddapalli',
      'Ramagiri',
      'Ramagundam',
      'Sulthanabad',
    ],
    'Rajanna Sircilla': [
      'Boinpalli',
      'Chandurthi',
      'Ellanthakunta',
      'Gambhiraopet',
      'Illanthakunta',
      'Konaraopet',
      'Mustabad',
      'Rudrangi',
      'Sircilla',
      'Thangallapalli',
      'Veernapalli',
      'Vemulawada',
      'Vemulawada Rural',
      'Yellareddypet',
    ],
    'Rangareddy': [
      'Abdullapurmet',
      'Amangal',
      'Chevella',
      'Farooqnagar (Shadnagar)',
      'Gandipet',
      'Hayathnagar',
      'Ibrahimpatnam',
      'Kadthal',
      'Kandukur',
      'Keshampet',
      'Kothur',
      'Madgul',
      'Maheswaram',
      'Manchal',
      'Moinabad',
      'Nandigama',
      'Rajendranagar',
      'Saroornagar',
      'Serilingampally (Gachibowli / Madhapur)',
      'Shabad',
      'Shamshabad',
      'Shankarpally',
      'Talakondapally',
      'Yacharam',
    ],
    'Sangareddy': [
      'Ameenpur',
      'Andole',
      'Gummadidala',
      'Hathnoora',
      'Jharasangam',
      'Kalher',
      'Kandi',
      'Kangti',
      'Kohir',
      'Kondapur',
      'Manoor',
      'Mogudampally',
      'Munipally',
      'Nagalgidda',
      'Narayankhed',
      'Nyalkal',
      'Patancheru',
      'Pulkal',
      'Raikode',
      'Ramachandrapuram',
      'Sadasivpet',
      'Sangareddy',
      'Sirgapoor',
      'Tellapur',
      'Vatpally',
      'Zaheerabad',
    ],
    'Siddipet': [
      'Bejjanki',
      'Cherial',
      'Chinnakodur',
      'Doultabad',
      'Dubbak',
      'Gajwel',
      'Husnabad',
      'Jagdevpur',
      'Koheda',
      'Komuravelli',
      'Kondapak',
      'Maddur',
      'Markook',
      'Mulug',
      'Nanganur',
      'Narayanraopet',
      'Raipole',
      'Siddipet Rural',
      'Siddipet Urban',
      'Thoguta',
      'Wargal',
    ],
    'Suryapet': [
      'Ananthagiri',
      'Atmakur (S)',
      'Chidurala',
      'Chilkur',
      'Chintalapalem',
      'Chivemla',
      'Garidepally',
      'Huzurnagar',
      'Jaji Reddi Gudem (Arvapally)',
      'Kodad',
      'Mallareddygudem',
      'Mattampally',
      'Mellachervu',
      'Mothey',
      'Munagala',
      'Nadigudem',
      'Nagaram',
      'Neredcherla',
      'Noothankal',
      'Palakeedu',
      'Penpahad',
      'Suryapet',
      'Thirumalagiri',
      'Thungathurthi',
    ],
    'Vikarabad': [
      'Bantwaram',
      'Basheerabad',
      'Bomraspet',
      'Choudapur',
      'Dharur',
      'Doma',
      'Doultabad',
      'Kodangal',
      'Kotepally',
      'Kulkacherla',
      'Marpalle',
      'Mominpet',
      'Nawabpet',
      'Parigi',
      'Pudur',
      'Tandur',
      'Vikarabad',
      'Yalal',
    ],
    'Wanaparthy': [
      'Amarchinta',
      'Atmakur',
      'Chinnambavi',
      'Ghanpur',
      'Gopalpeta',
      'Kothakota',
      'Madanapur',
      'Pangal',
      'Pebbair',
      'Revally',
      'Srirangapur',
      'Veepangandla',
      'Wanaparthy',
    ],
    'Warangal': [
      'Atmakur',
      'Chennaraopet',
      'Duggondi',
      'Geesugonda',
      'Inavole',
      'Khanapur',
      'Nallabelly',
      'Narsampet',
      'Nekkonda',
      'Parvathagiri',
      'Raiparthy',
      'Sangem',
      'Wardhannapet',
      'Warangal',
    ],
    'Yadadri Bhuvanagiri': [
      'Addagudur',
      'Alair',
      'Atmakur (M)',
      'B.Pochampally',
      'Bhuvanagiri',
      'Bibinagar',
      'Bommalaramaram',
      'Choutuppal',
      'Gundala',
      'Modukur',
      'Motakondur',
      'Mothkur',
      'Narayanpur',
      'Rajapet',
      'Ramannapeta',
      'Turkapally',
      'Valigonda',
      'Yadagirigutta',
    ],
  },
  'Karnataka': {
    'Bagalkote': [
      'Badami',
      'Bagalkote',
      'Bilgi',
      'Guledgudda',
      'Hungund',
      'Ilkal',
      'Jamkhandi',
      'Lokapur',
      'Mudhol',
      'Rabkavi Banhatti',
    ],
    'Ballari': [
      'Ballari Rural',
      'Ballari Urban',
      'Kampli',
      'Kurugodu',
      'Sandur',
      'Siruguppa',
    ],
    'Belagavi': [
      'Athani',
      'Bailhongal',
      'Belagavi',
      'Chikkodi',
      'Gokak',
      'Hukkeri',
      'Khanapur',
      'Mudalagi',
      'Nippani',
      'Ramdurg',
      'Raybag',
      'Saundatti',
    ],
    'Bengaluru Rural': [
      'Devanahalli',
      'Doddaballapura',
      'Hosakote',
      'Nelamangala',
    ],
    'Bengaluru Urban': [
      'Anekal',
      'Bengaluru East (Whitefield / KR Puram)',
      'Bengaluru North (Hebbal / Yelahanka / Malleshwaram)',
      'Bengaluru South (Koramangala / Jayanagar / HSR / E-City)',
      'Bengaluru West (Rajajinagar / Vijayanagar)',
    ],
    'Bidar': [
      'Aurad',
      'Basavakalyan',
      'Bhalki',
      'Bidar',
      'Chitguppa',
      'Hulsoor',
      'Humnabad',
      'Kamalnagar',
    ],
    'Chamarajanagar': [
      'Chamarajanagar',
      'Gundlupet',
      'Hanur',
      'Kollegal',
      'Yelandur',
    ],
    'Chikkaballapura': [
      'Bagepalli',
      'Chikkaballapura',
      'Chintamani',
      'Gauribidanur',
      'Gudibanda',
      'Sidlaghatta',
    ],
    'Chikkamagaluru': [
      'Ajjampura',
      'Chikkamagaluru',
      'Kadur',
      'Koppa',
      'Mudigere',
      'Narasimharajapura',
      'Sringeri',
      'Tarikere',
    ],
    'Chitradurga': [
      'Challakere',
      'Chitradurga',
      'Hiriyur',
      'Holalkere',
      'Hosadurga',
      'Molakalmuru',
    ],
    'Dakshina Kannada (Mangaluru)': [
      'Bantwal',
      'Belthangady',
      'Kadaba',
      'Mangaluru',
      'Moodabidri',
      'Puttur',
      'Sullia',
    ],
    'Davanagere': [
      'Channagiri',
      'Davanagere',
      'Harihara',
      'Honnali',
      'Jagalur',
      'Nyamathi',
    ],
    'Dharwad': [
      'Alnavar',
      'Annigeri',
      'Dharwad',
      'Hubballi Rural',
      'Hubballi Urban',
      'Kalghatgi',
      'Kundgol',
      'Navalgund',
    ],
    'Gadag': [
      'Betageri',
      'Gadag',
      'Gajendragad',
      'Lakshmeshwar',
      'Mundargi',
      'Nargund',
      'Ron',
      'Shirhatti',
    ],
    'Hassan': [
      'Alur',
      'Arkalgud',
      'Arsikere',
      'Belur',
      'Channarayapatna',
      'Hassan',
      'Holenarasipura',
      'Sakleshpur',
    ],
    'Haveri': [
      'Byadgi',
      'Hangal',
      'Haveri',
      'Hirekerur',
      'Ranebennur',
      'Rattihalli',
      'Savanur',
      'Shiggaon',
    ],
    'Kalaburagi': [
      'Afzalpur',
      'Aland',
      'Chincholi',
      'Chitapur',
      'Jevargi',
      'Kalaburagi Rural',
      'Kalaburagi Urban',
      'Kamalapur',
      'Sedam',
      'Shahabad',
      'Yadrami',
    ],
    'Kodagu (Coorg)': [
      'Kushalnagar',
      'Madikeri',
      'Ponnampet',
      'Somwarpet',
      'Virajpet',
    ],
    'Kolar': [
      'Bangarapet',
      'KGF (Robertsonpet)',
      'Kolar',
      'Malur',
      'Mulbagal',
      'Srinivaspur',
    ],
    'Koppal': [
      'Gangavathi',
      'Kanakagiri',
      'Karatagi',
      'Koppal',
      'Kukanoor',
      'Kushtagi',
      'Yelburga',
    ],
    'Mandya': [
      'Krishnarajpet (K.R.Pet)',
      'Maddur',
      'Malavalli',
      'Mandya',
      'Nagamangala',
      'Pandavapura',
      'Srirangapatna',
    ],
    'Mysuru': [
      'H.D.Kote',
      'Hunsur',
      'K.R.Nagar',
      'Mysuru Rural',
      'Mysuru Urban',
      'Nanjangud',
      'Piriyapatna',
      'Saragur',
      'T.Narasipura',
    ],
    'Raichur': [
      'Devadurga',
      'Lingsugur',
      'Manvi',
      'Maski',
      'Raichur',
      'Sindhanur',
      'Sirwar',
    ],
    'Ramanagara': [
      'Channapatna',
      'Harohalli',
      'Kanakapura',
      'Magadi',
      'Ramanagara',
    ],
    'Shivamogga': [
      'Bhadravathi',
      'Hosanagara',
      'Sagar',
      'Shikaripura',
      'Shivamogga',
      'Soraba',
      'Thirthahalli',
    ],
    'Tumakuru': [
      'Chikkanayakanahalli',
      'Gubbi',
      'Koratagere',
      'Kunigal',
      'Madhugiri',
      'Pavagada',
      'Sira',
      'Tiptur',
      'Tumakuru',
      'Turuvekere',
    ],
    'Udupi': [
      'Brahmavara',
      'Byndoor',
      'Hebri',
      'Karkala',
      'Kaup',
      'Kundapura',
      'Udupi',
    ],
    'Uttara Kannada (Karwar)': [
      'Ankola',
      'Bhatkal',
      'Dandeli',
      'Haliyal',
      'Honnavar',
      'Joida',
      'Karwar',
      'Kumta',
      'Mundgod',
      'Siddapur',
      'Sirsi',
      'Yellapur',
    ],
    'Vijayanagara': [
      'Hagaribommanahalli',
      'Harapanahalli',
      'Hoovina Hadagali',
      'Hosapete (Hampi)',
      'Kotturu',
      'Kudligi',
    ],
    'Vijayapura (Bijapur)': [
      'Babaleshwar',
      'Basavana Bagewadi',
      'Chadchan',
      'Devar Hippargi',
      'Indi',
      'Kolhar',
      'Muddebihal',
      'Nidagundi',
      'Sindagi',
      'Talikoti',
      'Tikota',
      'Vijayapura',
    ],
    'Yadgir': [
      'Gurmitkal',
      'Hunsagi',
      'Shahapur',
      'Shorapur',
      'Wadgera',
      'Yadgir',
    ],
  },
};

/**
 * Returns strictly alphabetical (A-Z) list of districts for a given state.
 */
export function getDistrictsForState(stateName: string): string[] {
  const matchedKey = SUPPORTED_STATES.find(
    (s) => s.toLowerCase() === stateName.trim().toLowerCase()
  );
  const stateData = (matchedKey && REGIONAL_GEO_DATA[matchedKey])
    ? REGIONAL_GEO_DATA[matchedKey]
    : REGIONAL_GEO_DATA['Andhra Pradesh'];

  return Object.keys(stateData).sort((a, b) => a.localeCompare(b));
}

/**
 * Returns strictly alphabetical (A-Z) list of mandals for a given state & district.
 */
export function getMandalsForDistrict(stateName: string, districtName: string): string[] {
  const matchedState = SUPPORTED_STATES.find(
    (s) => s.toLowerCase() === stateName.trim().toLowerCase()
  );
  if (matchedState && REGIONAL_GEO_DATA[matchedState]) {
    const districts = REGIONAL_GEO_DATA[matchedState];
    const matchedDistKey = Object.keys(districts).find(
      (d) =>
        d.toLowerCase() === districtName.trim().toLowerCase() ||
        d.toLowerCase().includes(districtName.trim().toLowerCase()) ||
        districtName.trim().toLowerCase().includes(d.toLowerCase())
    );
    if (matchedDistKey && districts[matchedDistKey]) {
      return [...districts[matchedDistKey]].sort((a, b) => a.localeCompare(b));
    }
  }
  return [];
}

/**
 * Matches detected state string to supported states, falling back to 'Andhra Pradesh'.
 */
export function normalizeSupportedState(rawState: string): SupportedState {
  const lower = rawState.trim().toLowerCase();
  if (lower.includes('telangana')) return 'Telangana';
  if (lower.includes('karnataka')) return 'Karnataka';
  return 'Andhra Pradesh';
}

/**
 * Curated Village & Locality database for Mandals
 */
export const MANDAL_VILLAGES_DATA: Record<string, string[]> = {
  // Andhra Pradesh
  'Undrajavaram': [
    'Chilakapadu',
    'Dammennu',
    'Kakaraparru',
    'Mortha',
    'Palangi',
    'Pasalapudi',
    'Satyavada',
    'Suryaraopalem',
    'Undrajavaram',
    'Vellamilli',
    'Yadhavapuram',
  ],
  'Tanuku': [
    'Duvva',
    'Kommaravaram',
    'Mandapaka',
    'Peravali Road',
    'Pydiparru',
    'Sajjapuram',
    'Tanuku Town',
    'Tetali',
    'Varadarajapuram',
    'Velpur',
  ],
  'Bhimavaram': [
    'Annavaram',
    'Bhimavaram Town',
    'Chinna Amiram',
    'Dirusumarru',
    'Gollalakoderu',
    'Kovvada',
    'Losarigutlapadu',
    'Rayalam',
    'Somavaram',
    'Yenamadurru',
  ],
  'Palakollu': [
    'Chintaparru',
    'Digamarru',
    'Goraganamudi',
    'Lankalakoderu',
    'Palakollu Town',
    'Poolapalli',
    'Ullamparru',
  ],
  'Narasapuram': [
    'Chitthanapadu',
    'L.B.Charla',
    'Mogalthur Road',
    'Narasapuram Town',
    'Peda Mainavanilanka',
    'Rustumbada',
  ],
  'Tadepalligudem': [
    'Apparaopeta',
    'Kondruprolu',
    'Kunchanapalli',
    'Madhavaram',
    'Padala',
    'Tadepalligudem Town',
  ],
  'Rajamahendravaram (Urban)': [
    'Aryapuram',
    'Danavaipeta',
    'Diwancheruvu',
    'Innespeta',
    'Kotipalli Bus Stand',
    'Lalacheruvu',
    'Morampudi',
  ],
  'Rajahmundry Rural': [
    'Bommuru',
    'Dowleswaram',
    'Hukumpeta',
    'Katheru',
    'Rajavolu',
    'Torredu',
  ],
  'Kakinada Urban': [
    'Bhanugudi Junction',
    'Cinema Road',
    'Jagannaickpur',
    'Madhavapatnam',
    'Sarpavaram',
    'Suryaraopeta',
  ],
  'Amalapuram': [
    'Amalapuram Town',
    'Avanigadda Road',
    'Bhatnavilli',
    'Edarapalli',
    'Indupalle',
    'Sampara',
  ],
  'Vijayawada Urban': [
    'Auto Nagar',
    'Benz Circle',
    'Bhavanipuram',
    'Governorpet',
    'Gunadala',
    'MG Road (Bandar Road)',
    'Patamata',
    'Satyanarayanapuram',
  ],
  'Guntur East': [
    'Autonagar',
    'Etukuru',
    'Kothapet',
    'Lalapet',
    'Old Guntur',
    'Sangadigunta',
  ],
  'Guntur West': [
    'Arundelpet',
    'Brodipet',
    'Gujaanagundla',
    'Koretipadu',
    'Pattabhipuram',
    'Vidyanagar',
  ],
  'Tirupati Urban': [
    'Alipiri',
    'Bhavani Nagar',
    'KT Road',
    'Korlagunta',
    'Leela Mahal',
    'MR Palli',
    'Tiruchanur',
  ],
  'Visakhapatnam Urban': [
    'Beach Road',
    'Dwaraka Nagar',
    'Gajuwaka',
    'MVP Colony',
    'Madhurawada',
    'Seethammadhara',
    'Siripuram',
  ],

  // Telangana
  'Vikarabad': [
    'Alampally',
    'Attapur',
    'Dharur Road',
    'Gangupally',
    'Gottimukla',
    'Madanpally',
    'Nawabpet Road',
    'Pudur',
    'Shivareddypally',
    'Sidloor',
    'Vikarabad Town',
  ],
  'Tandur': [
    'Belkatur',
    'Chincholi',
    'Gouthapur',
    'Karankote',
    'Kothlapur',
    'Malreddypally',
    'Rasoolpur',
    'Tandur Town',
  ],
  'Parigi': [
    'Chityal',
    'Gaggalapally',
    'Kollur',
    'Manchanpally',
    'Parigi Town',
    'Rakhicherla',
    'Rapole',
  ],
  'Kodangal': [
    'Appampally',
    'Gandhichowk',
    'Hasnapur',
    'Kodangal Town',
    'Parsapur',
    'Rampur',
    'Tekulkode',
  ],
  'Serilingampally (Gachibowli / Madhapur)': [
    'Chanda Nagar',
    'Financial District',
    'Gachibowli',
    'Hafeezpet',
    'Hitec City',
    'Kondapur',
    'Madhapur',
    'Miyapur',
    'Nanakramguda',
    'Raidurg',
  ],
  'Rajendranagar': [
    'Attapur',
    'Bandlaguda Jagir',
    'Budvel',
    'Hyderguda',
    'Kismatpur',
    'Upperpally',
  ],
  'Shamshabad': [
    'Airport Area',
    'Kotwalguda',
    'Madanpally',
    'Ootpally',
    'Pedda Golconda',
    'Tondupally',
  ],
  'Kukatpally': [
    'Bhagyanagar',
    'Hydernagar',
    'KPHB Colony',
    'Moosapet',
    'Nizampet Road',
    'Vivekananda Nagar',
  ],
  'Ameerpet': [
    'Ameerpet Centre',
    'Balkampet',
    'Dharam Karan Road',
    'Punjagutta',
    'SR Nagar',
    'Yellareddyguda',
  ],
  'Jubilee Hills': [
    'Banjara Hills Road 1-14',
    'Film Nagar',
    'Jubilee Hills Checkpost',
    'Nandagiri Hills',
    'Road No. 36',
    'Road No. 45',
    'Venkatagiri',
  ],
  'Khairatabad': [
    'Anand Nagar',
    'Chintal Basti',
    'Khairatabad Junction',
    'Raj Bhavan Road',
    'Somajiguda',
  ],
  'Secunderabad': [
    'Clock Tower',
    'Marredpally',
    'Paradise',
    'Patny',
    'Ranigunj',
    'Secunderabad Station',
    'Sindhi Colony',
  ],
  'Hanamkonda': [
    'Ashok Nagar',
    'Balasamudram',
    'Kakatiya University Campus',
    'Lashkar Bazaar',
    'Nakkalagutta',
    'Subedari',
  ],
  'Warangal': [
    'Deshaipet',
    'Fort Warangal',
    'Kareemabad',
    'MGM Hospital Area',
    'Pochamma Maidan',
  ],
  'Karimnagar': [
    'Collectorate Area',
    'Kothirampur',
    'Mankammathota',
    'Mukarampura',
    'Sapthagiri Colony',
    'Vavilalapalli',
  ],
  'Nizamabad Urban': [
    'Armoor Road',
    'Bodhan Road',
    'Dubba',
    'Khaleelwadi',
    'Subhashnagar',
    'Vinayak Nagar',
  ],

  // Karnataka
  'Bengaluru East (Whitefield / KR Puram)': [
    'Brookefield',
    'Hoodi',
    'Hope Farm',
    'ITPL',
    'KR Puram',
    'Kadugodi',
    'Mahadevapura',
    'Varthur',
    'Whitefield Main',
  ],
  'Bengaluru South (Koramangala / Jayanagar / HSR / E-City)': [
    'BTM Layout',
    'Bellandur',
    'Electronic City Phase 1 & 2',
    'HSR Layout Sector 1-7',
    'Jayanagar',
    'Koramangala 1st-8th Block',
    'Sarjapur Road',
  ],
  'Bengaluru North (Hebbal / Yelahanka / Malleshwaram)': [
    'Hebbal',
    'Jalahalli',
    'Malleshwaram',
    'RT Nagar',
    'Sahakar Nagar',
    'Sanjay Nagar',
    'Yelahanka New Town',
  ],
  'Bengaluru West (Rajajinagar / Vijayanagar)': [
    'Basaveshwaranagar',
    'Mahalakshmi Layout',
    'Nagarbhavi',
    'Rajajinagar',
    'Vijayanagar',
  ],
  'Mysuru Urban': [
    'Gokulam',
    'Jayalakshmipuram',
    'Karasthana',
    'Kuvempunagar',
    'Saraswathipuram',
    'Vijayanagar',
    'Yadavagiri',
  ],
  'Mangaluru': [
    'Bejai',
    'Hampankatta',
    'Kadri',
    'Kankanady',
    'Kodialbail',
    'Ladyhill',
    'Mannagudda',
    'Surathkal',
  ],
  'Udupi': [
    'Ambalpady',
    'Bannanje',
    'Kadiyali',
    'Malpe',
    'Manipal',
    'Santhekatte',
  ],
};

/**
 * Returns strictly alphabetical (A-Z) list of Villages / Localities for a given Mandal.
 * If specific curated villages exist, returns them.
 * Otherwise dynamically creates sensible alphabetical locality/village options for that Mandal.
 */
export function getVillagesForMandal(
  _stateName: string,
  _districtName: string,
  mandalName: string
): string[] {
  if (!mandalName || mandalName === 'CUSTOM') return [];

  // Match against curated list
  const matchedKey = Object.keys(MANDAL_VILLAGES_DATA).find(
    (k) =>
      k.toLowerCase() === mandalName.trim().toLowerCase() ||
      mandalName.trim().toLowerCase().includes(k.toLowerCase()) ||
      k.toLowerCase().includes(mandalName.trim().toLowerCase())
  );

  if (matchedKey && MANDAL_VILLAGES_DATA[matchedKey]) {
    return [...MANDAL_VILLAGES_DATA[matchedKey]].sort((a, b) => a.localeCompare(b));
  }

  // Clean raw mandal name
  const cleanName = mandalName.replace(/\s*\([^)]*\)/g, '').trim();

  // Algorithmic default village list for any other mandal
  const generated = [
    cleanName,
    `${cleanName} Central`,
    `${cleanName} Colony`,
    `${cleanName} East`,
    `${cleanName} Market`,
    `${cleanName} Rural`,
    `${cleanName} West`,
  ];

  return generated.sort((a, b) => a.localeCompare(b));
}

